Enum FeedbackSource {
  API
  MANUAL
}

Enum SegmentType {
  INTRODUCTION
  MAIN_POINT
  CONCLUSION
  TOPIC_SENTENCE
}

Table ieltssci_essays {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID của bài viết, dùng để tạo link share bài viết']
  original_id integer [note: 'ID bài gốc, sd khi gvien fork bài để nxet']
  ocr_image_ids integer[] [note: 'ID của ảnh người dùng upload']
  chart_image_ids integer[] [note: 'ID của ảnh biểu đồ người dùng upload']
  essay_type varchar [not null, note: 'Loại bài e.g Task 1, Task 2, Task 1 OCR, Task 2 OCR.']
  question varchar [not null, note: 'Câu hỏi của bài']
  essay_content text [not null, note: 'Nội dung bài viết']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID người tạo bài, nếu fork từ bài khác thì là ID của người fork']
}

Table ieltssci_essay_meta {
  meta_id integer [primary key, increment]
  ieltssci_essay_id integer [not null, note: 'FK to ieltssci_essays.']
  meta_key varchar [not null, note: 'e.g., overall_score, grading_rubric, etc.']
  meta_value text [not null, note: 'Value for the meta key.']
}

Table ieltssci_segment {
  id integer [primary key, increment]
  essay_id integer [not null]
  type SegmentType [not null, note: 'Loại đoạn e.g introduction, main point, conclusion, topic sentence']
  order integer [not null, note: 'Thứ tự đoạn trong bài']
  title text [not null, note: 'vd: Introduction, Main Point 1, Conclusion, etc.']
  content text [not null]
}

Table ieltssci_segment_feedback {
  id integer [primary key, increment]
  feedback_criteria varchar [not null, note: 'tiêu chí feedback e.g relevance, clearAnswer (score, Cot, feedback), rewrite, logicDepth, etc.']
  segment_id integer [not null]
  feedback_language varchar [not null, note: 'Ngôn ngữ của feedback']
  source FeedbackSource [not null]
  cot_content text [note: 'Nội dung phần COT']
  score_content text [note: 'Nội dung phần điểm số']
  feedback_content text [note: 'Nội dung phần feedback']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID của người call API hoặc update MANUAL feedback']
  is_preferred boolean [note: 'Feedback được chọn làm feedback mặc định cho đoạn này']
}

Table ieltssci_essay_feedback {
  id integer [primary key, increment]
  feedback_criteria varchar [not null, note: 'Tiêu chí feedback e.g relevance, clearAnswer (score, Cot, feedback), rewrite, logicDepth, etc.']
  essay_id integer [not null]
  feedback_language varchar [not null, note: 'Ngôn ngữ của feedback e.g English, Vietnamese']
  source FeedbackSource [not null]
  cot_content text [note: 'Nội dung phần COT']
  score_content text [note: 'Nội dung phần điểm số']
  feedback_content text [note: 'Nội dung phần feedback']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID của người call API hoặc update MANUAL feedback']
  is_preferred boolean [note: 'Feedback được chọn làm feedback mặc định cho bài này']
}

Table ieltssci_api_feed_essay_type {
  id integer [primary key, increment]
  api_feed_id integer [not null, note: 'ID của API feed']
  essay_type varchar [not null, note: 'loại bài e.g Task 1, Task 2, Task 1 OCR, Task 2 OCR.']
  process_order integer [not null, note: 'Thứ tự xử lý feed, vd: 2 feed cùng thứ tự 1 thì sử lý song song, cả 2 hoàn thành thì mới tiếp tục (các) feed thứ tự 2']
  dependencies integer[] [note: 'Các API feed khác mà API feed này phụ thuộc vào']
}

Table ieltssci_api_feed {
  id integer [primary key, increment]
  feed_title varchar [not null, note: 'Tiêu đề của API feed']
  feed_desc text [not null, note: 'Mô tả của API feed']
  feedback_criteria varchar [not null, note: 'Tiêu chí feedback e.g relevance, clearAnswer (score, Cot, feedback), rewrite, logicDepth, etc.']
  apply_to varchar [not null, note: 'Áp dụng cho cả bài hay từng đoạn, mở thân, kết, vv']
  meta json [not null, note: 'Setting cho API feed, base URL, parameters, step vv']
}

// Writing Tasks as CPT
Table wp_writing_tasks {
  id integer [primary key, increment]
}

// Writing Tests as CPT
Table wp_writing_tests {
  id integer [primary key, increment]
  task_ids integer[] [not null, note: 'ID của bài viết trong wp_writing_tasks']
}

Table ieltssci_writing_test_submissions {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID of the test submission, used for creating share links']
  test_id integer [not null, note: 'ID of the test from wp_writing_tests.']
  user_id integer [not null, note: 'ID of the user who submitted the test.']
  status varchar [not null, default: 'in-progress', note: 'e.g., in-progress, completed, graded.']
  started_at timestamp [note: 'Timestamp when the test was started.']
  updated_at timestamp [note: 'Timestamp when the test was last updated.']
  completed_at timestamp [note: 'Timestamp when the test was completed.']
}

Table ieltssci_writing_task_submissions {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID of the task submission, used for creating share links']
  test_submission_id integer [note: 'ID of the test submission from ieltssci_writing_test_submissions, nullable if standalone.']
  user_id integer [not null, note: 'ID of the user who submitted the test.']
  task_id integer [not null, note: 'ID of the writing task from wp_writing_tasks.']
  status varchar [not null, default: 'in-progress', note: 'e.g., in-progress, completed, graded.']
  essay_id integer [not null, note: 'ID of the essay from ieltssci_essays.']
  started_at timestamp [note: 'Timestamp when the task was started.']
  updated_at timestamp [note: 'Timestamp when the task was last updated.']
  completed_at timestamp [note: 'Timestamp when the task was completed.']
}

Table ieltssci_writing_test_submission_meta {
  meta_id integer [primary key, increment]
  ieltssci_writing_test_submission_id integer [not null, note: 'FK to ieltssci_writing_test_submissions.']
  meta_key varchar [not null, note: 'e.g., time_elapsed, time_limit, etc.']
  meta_value text [note: 'Value for the meta key.']
}

Table ieltssci_writing_task_submission_meta {
  meta_id integer [primary key, increment]
  ieltssci_writing_task_submission_id integer [not null, note: 'FK to ieltssci_writing_task_submissions.']
  meta_key varchar [not null, note: 'e.g., time_elapsed, time_limit, etc.']
  meta_value text [note: 'Value for the meta key.']
}

// Relationships
Ref: wp_writing_tests.id < ieltssci_writing_test_submissions.test_id
Ref: ieltssci_writing_test_submissions.id < ieltssci_writing_task_submissions.test_submission_id
Ref: wp_writing_tasks.id < ieltssci_writing_task_submissions.task_id
Ref: ieltssci_essays.id < ieltssci_writing_task_submissions.essay_id
Ref: ieltssci_writing_test_submissions.id < ieltssci_writing_test_submission_meta.ieltssci_writing_test_submission_id
Ref: ieltssci_writing_task_submissions.id < ieltssci_writing_task_submission_meta.ieltssci_writing_task_submission_id


Table ieltssci_rate_limit_rule {
  id integer [primary key, increment]
  rate_limit integer [not null, note: 'Số lần request cho phép trong 1 khoảng thời gian']
  time_period_type LimitType [not null, note: 'Loại giới hạn, theo thời gian, theo lịch, vĩnh viễn']
  limit_rule json [not null, note: 'Chi tiết rule, ví dụ: {"time_period": 1, "unit": "month"}']
  message json [not null, note: 'Thông báo khi vượt quá rate limit']
}

Table ieltssci_api_feed_rate_limit_rule {
  id integer [primary key, increment]
  api_feed_id integer [not null, note: 'ID của API feed']
  rate_limit_rule_id integer [not null, note: 'ID của rule áp dụng cho API feed']
}

Table ieltssci_role_rate_limit_rule {
  id integer [primary key, increment]
  role varchar [not null, note: 'User role']
  rate_limit_rule_id integer [not null, note: 'ID of the rate limit rule']
}

// Relationships

Table ieltssci_api_request_log {
  id integer [primary key, increment]
  created_by integer [not null, note: 'ID của người call API']
  api_feed_id integer [not null, note: 'Related API feed id']
  request_method varchar [not null, note: 'HTTP method e.g., GET, POST']
  request_url varchar [not null, note: 'The URL of the API request']
  request_headers json [note: 'Request headers']
  request_body json [note: 'Request payload']
  response_status integer [not null, note: 'HTTP status code of the response']
  response_headers json [note: 'Response headers']
  response_body json [note: 'Response payload']
  created_at timestamp [default: `now()`]
}

Table ieltssci_api_key {
  id integer [primary key, increment]
  api_provider varchar [not null, note: 'The API provider, e.g., OpenAI, Azure, etc.']
  meta json [note: 'API keys and other settings']
  usage_count integer [default: 0, note: 'The number of times the API key has been used']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Enum LimitType {
  Forever
  TimePeriod
  CalendarPeriod
}

// Relationships
Ref: ieltssci_essays.id < ieltssci_segment.essay_id
Ref: ieltssci_segment.id < ieltssci_segment_feedback.segment_id
Ref: ieltssci_essays.id < ieltssci_essay_feedback.essay_id
Ref: ieltssci_essays.id < ieltssci_essay_meta.ieltssci_essay_id
Ref: ieltssci_api_feed.id < ieltssci_api_feed_rate_limit_rule.api_feed_id
Ref: ieltssci_rate_limit_rule.id < ieltssci_api_feed_rate_limit_rule.rate_limit_rule_id
Ref: ieltssci_api_feed.feedback_criteria < ieltssci_segment_feedback.feedback_criteria
Ref: ieltssci_api_feed.feedback_criteria < ieltssci_essay_feedback.feedback_criteria
Ref: ieltssci_api_feed.id < ieltssci_api_request_log.api_feed_id
Ref: ieltssci_rate_limit_rule.id < ieltssci_role_rate_limit_rule.rate_limit_rule_id
Ref: ieltssci_api_feed.id < ieltssci_api_feed_essay_type.api_feed_id

// Speaking related tables

Table ieltssci_speech {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID của bài nói, dùng để tạo link share bài nói']
  audio_ids text [not null, note: 'ID của file audio người dùng upload']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID người tạo bài, nếu fork từ bài khác thì là ID của người fork']
}

// Speech meta data
Table ieltssci_speech_meta {
  meta_id integer [primary key, increment]
  ieltssci_speech_id integer [not null, note: 'FK to ieltssci_speech.']
  meta_key varchar [not null, note: 'e.g., overall_score, grading_rubric, etc.']
  meta_value text [not null, note: 'Value for the meta key.']
}

Ref: ieltssci_speech.id < ieltssci_speech_meta.ieltssci_speech_id

Table ieltssci_speech_feedback {
  id integer [primary key, increment]
  feedback_criteria varchar [not null, note: 'Tiêu chí feedback e.g relevance, clearAnswer, rewrite, logicDepth, etc.']
  speech_id integer [not null]
  feedback_language varchar [not null, note: 'Ngôn ngữ của feedback e.g English, Vietnamese']
  source FeedbackSource [not null, note: 'Nguồn của feedback']
  cot_content text [note: 'Nội dung phần COT']
  score_content text [note: 'Nội dung phần điểm số']
  feedback_content text [note: 'Nội dung phần feedback']
  is_preferred boolean [default: false, note: 'Feedback được chọn làm feedback mặc định']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID của người call API hoặc update MANUAL feedback']
}

// Relationships
Ref: ieltssci_speech.id < ieltssci_speech_feedback.speech_id

// Speaking Parts as CPT
Table wp_speaking_parts {
  id integer [primary key, increment]
}

// Speaking Tests as CPT
Table wp_speaking_tests {
  id integer [primary key, increment]
  part_ids integer[] [not null, note: 'ID của các phần nói trong wp_speaking_parts']
}

Table ieltssci_speaking_test_submissions {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID of the speaking test submission, used for creating share links']
  test_id integer [not null, note: 'ID of the test from wp_speaking_tests.']
  user_id integer [not null, note: 'ID of the user who submitted the test.']
  status varchar [not null, default: 'in-progress', note: 'e.g., in-progress, completed, graded.']
  started_at timestamp [note: 'Timestamp when the test was started.']
  updated_at timestamp [note: 'Timestamp when the test was last updated.']
  completed_at timestamp [note: 'Timestamp when the test was completed.']
}

Table ieltssci_speaking_part_submissions {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID of the speaking part submission, used for creating share links']
  test_submission_id integer [note: 'ID of the test submission from ieltssci_speaking_test_submissions, nullable if standalone.']
  user_id integer [not null, note: 'ID of the user who submitted the test.']
  part_id integer [not null, note: 'ID of the speaking part from wp_speaking_parts.']
  status varchar [not null, default: 'in-progress', note: 'e.g., in-progress, completed, graded.']
  speech_id integer [not null, note: 'ID of the speech from ieltssci_speech.']
  started_at timestamp [note: 'Timestamp when the part was started.']
  updated_at timestamp [note: 'Timestamp when the part was last updated.']
  completed_at timestamp [note: 'Timestamp when the part was completed.']
}

Table ieltssci_speaking_test_submission_meta {
  meta_id integer [primary key, increment]
  ieltssci_speaking_test_submission_id integer [not null, note: 'FK to ieltssci_speaking_test_submissions.']
  meta_key varchar [not null, note: 'e.g., time_elapsed, time_limit, etc.']
  meta_value text [note: 'Value for the meta key.']
}

Table ieltssci_speaking_part_submission_meta {
  meta_id integer [primary key, increment]
  ieltssci_speaking_part_submission_id integer [not null, note: 'FK to ieltssci_speaking_part_submissions.']
  meta_key varchar [not null, note: 'e.g., time_elapsed, time_limit, etc.']
  meta_value text [note: 'Value for the meta key.']
}

// Relationships
Ref: wp_speaking_tests.id < ieltssci_speaking_test_submissions.test_id
Ref: ieltssci_speaking_test_submissions.id < ieltssci_speaking_part_submissions.test_submission_id
Ref: wp_speaking_parts.id < ieltssci_speaking_part_submissions.part_id
Ref: ieltssci_speech.id < ieltssci_speaking_part_submissions.speech_id
Ref: ieltssci_speaking_test_submissions.id < ieltssci_speaking_test_submission_meta.ieltssci_speaking_test_submission_id
Ref: ieltssci_speaking_part_submissions.id < ieltssci_speaking_part_submission_meta.ieltssci_speaking_part_submission_id