Enum FeedbackSource {
  API
  MANUAL
}

Enum SegmentType {
  INTRODUCTION
  MAIN_POINT
  CONCLUSION
  TOPIC_SENTENCE
}

Table ieltssci_essays {
  id integer [primary key, increment]
  uuid varchar [not null, unique, note: 'UUID của bài viết, dùng để tạo link share bài viết']
  original_id integer [note: 'ID bài gốc, sd khi gvien fork bài để nxet']
  ocr_image_ids integer[] [note: 'ID của ảnh người dùng upload']
  chart_image_ids integer[] [note: 'ID của ảnh biểu đồ người dùng upload']
  essay_type varchar [not null, note: 'Loại bài e.g Task 1, Task 2, Task 1 OCR, Task 2 OCR.']
  question varchar [not null, note: 'Câu hỏi của bài']
  essay_content text [not null, note: 'Nội dung bài viết']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID người tạo bài, nếu fork từ bài khác thì là ID của người fork']
}

Table ieltssci_segment {
  id integer [primary key, increment]
  essay_id integer [not null]
  type SegmentType [not null, note: 'Loại đoạn e.g introduction, main point, conclusion, topic sentence']
  order integer [not null, note: 'Thứ tự đoạn trong bài']
  title text [not null, note: 'vd: Introduction, Main Point 1, Conclusion, etc.']
  content text [not null]
}

Table ieltssci_segment_feedback {
  id integer [primary key, increment]
  feedback_criteria varchar [not null, note: 'tiêu chí feedback e.g relevance, clearAnswer (score, Cot, feedback), rewrite, logicDepth, etc.']
  segment_id integer [not null]
  feedback_language varchar [not null, note: 'Ngôn ngữ của feedback']
  source FeedbackSource [not null]
  cot_content text [note: 'Nội dung phần COT']
  score_content text [note: 'Nội dung phần điểm số']
  feedback_content text [note: 'Nội dung phần feedback']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID của người call API hoặc update MANUAL feedback']
  is_preferred boolean [note: 'Feedback được chọn làm feedback mặc định cho đoạn này']
}

Table ieltssci_essay_feedback {
  id integer [primary key, increment]
  feedback_criteria varchar [not null, note: 'Tiêu chí feedback e.g relevance, clearAnswer (score, Cot, feedback), rewrite, logicDepth, etc.']
  essay_id integer [not null]
  feedback_language varchar [not null, note: 'Ngôn ngữ của feedback e.g English, Vietnamese']
  source FeedbackSource [not null]
  cot_content text [note: 'Nội dung phần COT']
  score_content text [note: 'Nội dung phần điểm số']
  feedback_content text [note: 'Nội dung phần feedback']
  created_at timestamp [default: `now()`]
  created_by integer [not null, note: 'ID của người call API hoặc update MANUAL feedback']
  is_preferred boolean [note: 'Feedback được chọn làm feedback mặc định cho bài này']
}

Table ieltssci_api_feed_essay_type {
  id integer [primary key, increment]
  api_feed_id integer [not null, note: 'ID của API feed']
  essay_type varchar [not null, note: 'loại bài e.g Task 1, Task 2, Task 1 OCR, Task 2 OCR.']
  process_order integer [not null, note: 'Thứ tự xử lý feed, vd: 2 feed cùng thứ tự 1 thì sử lý song song, cả 2 hoàn thành thì mới tiếp tục (các) feed thứ tự 2']
  dependencies integer[] [note: 'Các API feed khác mà API feed này phụ thuộc vào']
}

Table ieltssci_api_feed {
  id integer [primary key, increment]
  feed_title varchar [not null, note: 'Tiêu đề của API feed']
  feed_desc text [not null, note: 'Mô tả của API feed']
  feedback_criteria varchar [not null, note: 'Tiêu chí feedback e.g relevance, clearAnswer (score, Cot, feedback), rewrite, logicDepth, etc.']
  apply_to varchar [not null, note: 'Áp dụng cho cả bài hay từng đoạn, mở thân, kết, vv']
  meta json [not null, note: 'Setting cho API feed, base URL, parameters, step vv']
}

Table ieltssci_rate_limit_rule {
  id integer [primary key, increment]
  rate_limit integer [not null, note: 'Số lần request cho phép trong 1 khoảng thời gian']
  time_period_type LimitType [not null, note: 'Loại giới hạn, theo thời gian, theo lịch, vĩnh viễn']
  limit_rule json [not null, note: 'Chi tiết rule, ví dụ: {"time_period": 1, "unit": "month"}']
  message json [not null, note: 'Thông báo khi vượt quá rate limit']
}

Table ieltssci_api_feed_rate_limit_rule {
  id integer [primary key, increment]
  api_feed_id integer [not null, note: 'ID của API feed']
  rate_limit_rule_id integer [not null, note: 'ID của rule áp dụng cho API feed']
}

Table ieltssci_role_rate_limit_rule {
  id integer [primary key, increment]
  role varchar [not null, note: 'User role']
  rate_limit_rule_id integer [not null, note: 'ID of the rate limit rule']
}

// Relationships

Table ieltssci_api_request_log {
  id integer [primary key, increment]
  created_by integer [not null, note: 'ID của người call API']
  api_feed_id integer [not null, note: 'Related API feed id']
  request_method varchar [not null, note: 'HTTP method e.g., GET, POST']
  request_url varchar [not null, note: 'The URL of the API request']
  request_headers json [note: 'Request headers']
  request_body json [note: 'Request payload']
  response_status integer [not null, note: 'HTTP status code of the response']
  response_headers json [note: 'Response headers']
  response_body json [note: 'Response payload']
  created_at timestamp [default: `now()`]
}

Table ieltssci_api_key {
  id integer [primary key, increment]
  api_provider varchar [not null, note: 'The API provider, e.g., OpenAI, Azure, etc.']
  meta json [note: 'API keys and other settings']
  usage_count integer [default: 0, note: 'The number of times the API key has been used']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Enum LimitType {
  Forever
  TimePeriod
  CalendarPeriod
}

// Relationships
Ref: ieltssci_essays.id < ieltssci_segment.essay_id
Ref: ieltssci_segment.id < ieltssci_segment_feedback.segment_id
Ref: ieltssci_essays.id < ieltssci_essay_feedback.essay_id
Ref: ieltssci_api_feed.id < ieltssci_api_feed_rate_limit_rule.api_feed_id
Ref: ieltssci_rate_limit_rule.id < ieltssci_api_feed_rate_limit_rule.rate_limit_rule_id
Ref: ieltssci_api_feed.feedback_criteria < ieltssci_segment_feedback.feedback_criteria
Ref: ieltssci_api_feed.feedback_criteria < ieltssci_essay_feedback.feedback_criteria
Ref: ieltssci_api_feed.id < ieltssci_api_request_log.api_feed_id
Ref: ieltssci_rate_limit_rule.id < ieltssci_role_rate_limit_rule.rate_limit_rule_id
Ref: ieltssci_api_feed.id < ieltssci_api_feed_essay_type.api_feed_id